openapi: 3.0.0
info:
  title: Home
  version: '1.0'
  description: 'Адрес хоста для запросов: https://cloud.speechanalytics.ru/'
servers:
  - url: 'http://dev.peechanalytics'
    description: dev
  - url: 'https://cloud.speechanalytics.ru'
    description: prod
paths:
  /auth/login:
    $ref: 'https://github.com/kamirt/sa-api/blob/master/reference/home/paths/login.yaml'
  /account/available_accounts:
    get:
      summary: Available Accounts
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
              examples:
                Успешный ответ:
                  value:
                    - id: 100203
                      name: Test Account
                    - id: 500448
                      name: New pilot
                    - id: 612306
                      name: sipuni_test
      description: '### Список доступных аккаунтов'
    parameters: []
  /account:
    get:
      summary: Get Account
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  status:
                    type: string
              examples:
                example-1:
                  value:
                    id: 100203
                    status: VALID
      description: '### Узнать текущий аккаунт'
components:
  schemas: {}
  securitySchemes:
    Basic:
      type: http
      scheme: Basic
      description: cookies and header
